# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obbkit < Formula
  desc ""
  homepage "https://github.com/Onboardbase/obbkit"
  version "0.0.7"

  on_macos do
    url "https://github.com/Onboardbase/obbkit/releases/download/v0.0.7/obbkit_0.0.7_Darwin_all.tar.gz"
    sha256 "e4f74fc46d934f487c7cad7e410d9609973a3126460f03e56f1a844155ed7bd4"

    def install
      bin.install "obbkit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Onboardbase/obbkit/releases/download/v0.0.7/obbkit_0.0.7_Linux_arm64.tar.gz"
      sha256 "2529b43c08f91f4518401b2639701c7b6213af1a53c918e883771e0f78ae42e5"

      def install
        bin.install "obbkit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/obbkit/releases/download/v0.0.7/obbkit_0.0.7_Linux_x86_64.tar.gz"
      sha256 "6749d6e11487326130144863b0969247fc574b2af15800c6fa32287cf7894bc4"

      def install
        bin.install "obbkit"
      end
    end
  end
end
