# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obbkit < Formula
  desc ""
  homepage "https://github.com/Onboardbase/obbkit"
  version "0.0.1"

  on_macos do
    url "https://github.com/Onboardbase/obbkit/releases/download/v0.0.1/obbkit_0.0.1_Darwin_all.tar.gz"
    sha256 "0105f8b4240125c272c06d428d81a01d90b41fca8dfdfa53dcf64b225b2d5ea6"

    def install
      bin.install "obbkit"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/obbkit/releases/download/v0.0.1/obbkit_0.0.1_Linux_x86_64.tar.gz"
      sha256 "9d4f665d7387f450e3a1326d34c21d6845302a30da8c9b3f22f8a0834634ff5b"

      def install
        bin.install "obbkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Onboardbase/obbkit/releases/download/v0.0.1/obbkit_0.0.1_Linux_arm64.tar.gz"
      sha256 "e878c92e8e23bd924576c9f7cfa23aef24d0ee8e19c4e225e63ac23f6f976174"

      def install
        bin.install "obbkit"
      end
    end
  end
end
